elsass_seeraiwer_rest:
    type: rest
    resource: "@ElsassSeeraiwerRestBundle/Resources/config/routing.yml"
    prefix:   /api

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

elsass_seeraiwer_es_demo:
    resource: "@ElsassSeeraiwerESDemoBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    defaults:
        _locale: en
    requirements:
        _locale: en|fr

_welcome:
    pattern:  /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /en/
        permanent: true

# ESBarBundle

#elsass_seeraiwer_es_bar:
#    resource: "@ElsassSeeraiwerESBarBundle/Controller/"
#    type:     annotation
#    prefix:   /{_locale}
#    defaults:
#        _locale: en
#    requirements:
#        _locale: en|fr

# FOSUserBundle

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:   /{_locale}
    defaults:
        _locale: en
    requirements:
        _locale: en|fr

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile
    defaults:
        _locale: en
    requirements:
        _locale: en|fr

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register
    defaults:
        _locale: en
    requirements:
        _locale: en|fr

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting
    defaults:
        _locale: en
    requirements:
        _locale: en|fr

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/profile
    defaults:
        _locale: en
    requirements:
        _locale: en|fr